author: Aa Y

keywords: Hexo, Theme-AD

description: Yaa's Blog

# 导航栏头部名称
nav_name: Yaa

# 导航栏座右铭
motto: "Blog"

github: "https://github.com/zyayoung/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "Yaa"
  show_link: true
  more: '转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-05-01"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: fmmQ5HHXBeCLVf0DYXAfyBnM-gzGzoHsz # 填写您的appid
  appkey: WaRxtuWpVWcnAiqd2erlT4vy # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.count为true
welcome: 
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus: 
  enable: false
  id: 

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: false
  facebook: false
  weibo: true
  qq: true
  wechat: true

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id: 
  "360":
    enable: false
    id: 

reward:
  # -
  #   src: /images/wechat.png
  #   alt: "WeChat"
  # -
  #   src: /images/alipay.png
  #   alt: "AliPay"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  # -
  #   name: "友链"
  #   path: "/friends/"
  -
    name: "关于"
    path: "/about/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "Scarlet Devil Mansion"
        path: "https://scarlet-climax.github.io/"

footer_contact: "Email: 1328410180@qq.com"

friends_avatar_cdn: 
friends:
  # -
  #   nickname: GodBMW
  #   avatar: /images/friends/godbmw.jpeg
  #   site: https://godbmw.com/
  #   meta: 主题作者
  #   show: true